## Import data

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv(r'C:\Users\Dell lap\Desktop\training\Machine Learning\conda-ai-ml-dl\diabetes_data_train_710samples.csv')

In [3]:
dataset.head()

Row  preg_count  glucose_concentration  diastolic_bp  \
0    0           6                    148            72   
1    1           1                     85            66   
2    2           8                    183            64   
3    3           1                     89            66   
4    4           0                    137            40   

   triceps_skin_fold_thickness  two_hr_serum_insulin   bmi  diabetes_pedi  \
0                           35                     0  33.6          0.627   
1                           29                     0  26.6          0.351   
2                            0                     0  23.3          0.672   
3                           23                    94  28.1          0.167   
4                           35                   168  43.1          2.288   

   age  diabetes_class  
0   50               1  
1   31               0  
2   32               1  
3   21               0  
4   33               1

In [4]:
dataset.corr()

Row  preg_count  glucose_concentration  \
Row                          1.000000   -0.049529              -0.003177   
preg_count                  -0.049529    1.000000               0.137212   
glucose_concentration       -0.003177    0.137212               1.000000   
diastolic_bp                -0.011381    0.142042               0.146026   
triceps_skin_fold_thickness  0.003161   -0.096404               0.055279   
two_hr_serum_insulin         0.005083   -0.069093               0.327807   
bmi                         -0.012753    0.020589               0.220797   
diabetes_pedi               -0.030718   -0.048586               0.139026   
age                         -0.007847    0.546881               0.277794   
diabetes_class              -0.063441    0.230506               0.458086   

                             diastolic_bp  triceps_skin_fold_thickness  \
Row                             -0.011381                     0.003161   
preg_count                       0.142042                    -0.096404   
glucose_concentration            0.146026                     0.055279   
diastolic_bp                     1.000000                     0.211979   
triceps_skin_fold_thickness      0.211979                     1.000000   
two_hr_serum_insulin             0.101921                     0.440467   
bmi                              0.279390                     0.385673   
diabetes_pedi                    0.040030                     0.181029   
age                              0.237515                    -0.116000   
diabetes_class                   0.058391                     0.084880   

                             two_hr_serum_insulin       bmi  diabetes_pedi  \
Row                                      0.005083 -0.012753      -0.030718   
preg_count                              -0.069093  0.020589      -0.048586   
glucose_concentration                    0.327807  0.220797       0.139026   
diastolic_bp                             0.101921  0.279390       0.040030   
triceps_skin_fold_thickness              0.440467  0.385673       0.181029   
two_hr_serum_insulin                     1.000000  0.200392       0.189800   
bmi                                      0.200392  1.000000       0.138409   
diabetes_pedi                            0.189800  0.138409       1.000000   
age                                     -0.026111  0.036475       0.036862   
diabetes_class                           0.137614  0.291296       0.172729   

                                  age  diabetes_class  
Row                         -0.007847       -0.063441  
preg_count                   0.546881        0.230506  
glucose_concentration        0.277794        0.458086  
diastolic_bp                 0.237515        0.058391  
triceps_skin_fold_thickness -0.116000        0.084880  
two_hr_serum_insulin        -0.026111        0.137614  
bmi                          0.036475        0.291296  
diabetes_pedi                0.036862        0.172729  
age                          1.000000        0.231088  
diabetes_class               0.231088        1.000000

## features = X, target = y

In [8]:
X = dataset.iloc[:, 1:9].values
y = dataset.iloc[:, 9].values

## split data into train and test

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
print(len(X_test), len(X_train), len(y_test), len(y_train))

142 568 142 568


## ANN- Start to build the network
### Import from keras

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [17]:
classifier = Sequential()

In [18]:
classifier.add(Dense(input_dim = 8,activation = 'relu', kernel_initializer = 'uniform',units = 4))

In [19]:
classifier.add(Dense(activation = 'sigmoid', kernel_initializer = 'uniform',units = 1))

In [20]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [22]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 200)

Epoch 1/200
568/568 [==============================] - 0s 206us/step - loss: 0.5543 - acc: 0.7183
Epoch 2/200
568/568 [==============================] - 0s 203us/step - loss: 0.5531 - acc: 0.7165
Epoch 3/200
568/568 [==============================] - 0s 160us/step - loss: 0.5615 - acc: 0.7218
Epoch 4/200
568/568 [==============================] - 0s 167us/step - loss: 0.5516 - acc: 0.7289
Epoch 5/200
568/568 [==============================] - 0s 217us/step - loss: 0.5532 - acc: 0.7324
Epoch 6/200
568/568 [==============================] - 0s 199us/step - loss: 0.5537 - acc: 0.7130 0s - loss: 0.5526 - acc: 0.714
Epoch 7/200
568/568 [==============================] - 0s 181us/step - loss: 0.5518 - acc: 0.7306
Epoch 8/200
568/568 [==============================] - 0s 213us/step - loss: 0.5490 - acc: 0.7342
Epoch 9/200
568/568 [==============================] - 0s 217us/step - loss: 0.5594 - acc: 0.7289
Epoch 10/200
568/568 [==============================] - 0s 206us/step - loss: 0.5551 - 

568/568 [==============================] - 0s 213us/step - loss: 0.5243 - acc: 0.7447
Epoch 84/200
568/568 [==============================] - 0s 227us/step - loss: 0.5267 - acc: 0.7377
Epoch 85/200
568/568 [==============================] - 0s 217us/step - loss: 0.5287 - acc: 0.7535
Epoch 86/200
568/568 [==============================] - 0s 208us/step - loss: 0.5254 - acc: 0.7447
Epoch 87/200
568/568 [==============================] - 0s 206us/step - loss: 0.5284 - acc: 0.7535
Epoch 88/200
568/568 [==============================] - 0s 227us/step - loss: 0.5255 - acc: 0.7518
Epoch 89/200
568/568 [==============================] - 0s 181us/step - loss: 0.5218 - acc: 0.7482
Epoch 90/200
568/568 [==============================] - 0s 213us/step - loss: 0.5215 - acc: 0.7518
Epoch 91/200
568/568 [==============================] - 0s 190us/step - loss: 0.5243 - acc: 0.7500
Epoch 92/200
568/568 [==============================] - 0s 233us/step - loss: 0.5310 - acc: 0.7447
Epoch 93/200
568/568 [=

568/568 [==============================] - 0s 215us/step - loss: 0.5118 - acc: 0.7465
Epoch 165/200
568/568 [==============================] - 0s 199us/step - loss: 0.5103 - acc: 0.7570
Epoch 166/200
568/568 [==============================] - 0s 262us/step - loss: 0.5169 - acc: 0.7465
Epoch 167/200
568/568 [==============================] - 0s 204us/step - loss: 0.5136 - acc: 0.7553
Epoch 168/200
568/568 [==============================] - 0s 218us/step - loss: 0.5102 - acc: 0.7500
Epoch 169/200
568/568 [==============================] - 0s 231us/step - loss: 0.5164 - acc: 0.7535
Epoch 170/200
568/568 [==============================] - 0s 211us/step - loss: 0.5220 - acc: 0.7394
Epoch 171/200
568/568 [==============================] - 0s 218us/step - loss: 0.5084 - acc: 0.7535
Epoch 172/200
568/568 [==============================] - 0s 257us/step - loss: 0.5000 - acc: 0.7535
Epoch 173/200
568/568 [==============================] - 0s 321us/step - loss: 0.5201 - acc: 0.7482
Epoch 174/200


In [ ]:
#8 weights * 4 weights at the hidden layer = 32 weights

In [ ]:
epoc 1 : 32 weights but I only 568 chances to get it right
epoc 1 :   568

In [35]:
y_pred = classifier.predict(X_test)

In [37]:
y_pred =  y_pred > 0.5 

In [38]:
y_pred[:5]

array([[ True],
       [False],
       [False],
       [ True],
       [False]])

In [39]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [40]:
cm

array([[89,  4],
       [24, 25]], dtype=int64)

In [42]:
len(y_test[y_test ==1])

49

In [43]:
len(y_test[y_test==0])

93

In [44]:
93/(93+49)

0.6549295774647887

In [51]:
len(y_pred)

142

In [52]:
classifier

In [53]:
classifier.predict(np.array([[2,120,72,45,0,28,0.627,42]]))

array([[0.19790569]], dtype=float32)

In [54]:
# you do not have diabetes and I am 80% confident